name: "simple-build-test"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "master"
    paths:
      - "Dockerfile*"
      - "Makefile"

jobs:
  docker_buildx_debian:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build the amd64 version of the Debian image
        run: make all


  docker_buildx_alpine:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build the amd64 version of the Alpine image
        run: make all-alpine
